name: e_commerce
description: A new Flutter project with Clean Architecture by Abdalluh Essam
# Flutter version on machine: 3.29.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: 
  animator: 
  cached_network_image: 
  cupertino_icons: 
  dartz: 
  dio: ^5.8.0+1
  easy_localization: 
  equatable: 
  firebase_auth: ^5.6.0
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_animate: 
  flutter_bloc: 
  flutter_credit_card: ^4.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: 
  flutter_native_splash: 
  flutter_screenutil: 
  flutter_stripe: 
  flutter_svg: 
  font_awesome_flutter: ^10.8.0
  freezed_annotation: 
  get_it: 
  google_fonts: 
  intl: 
  json_annotation: 
  lottie: 
  path: ^1.9.0


dev_dependencies:
  bloc_test: 
  build_runner: 
  flutter_lints: 
  flutter_test:
    sdk: flutter
  freezed: 
  json_serializable: 
  mockito: 

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/lang/
    - .env

